In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_excel('data/ITSM_Data.xlsx')
df.head()

,ID_request,Text,Category,Solution,Date_request_recieved,Date_request_solved,ID_agent
0,2913,Discord issue,Discord,Problem solved,2022-10-03,2022-10-03,3
1,2691,I need to install Discord on my new PC.,Discord,Discord Installed,2022-10-08,2022-10-10,1
2,3395,Discord disappeared from laptop after I update...,Discord,Discord Installed,2022-10-17,2022-10-17,3
3,2380,Discord is very slow while other applications ...,Discord,"Software updated, PC cleaned.",2022-10-11,2022-10-11,2
4,4999,Discor needed for instalation.,Discord,Problem solved,2022-10-04,2022-10-04,2

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118 entries, 0 to 117
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID_request             118 non-null    int64
 1   Text                   117 non-null    object
 2   Category               115 non-null    object
 3   Solution               115 non-null    object
 4   Date_request_recieved  118 non-null    datetime64[ns]
 5   Date_request_solved    118 non-null    datetime64[ns]
 6   ID_agent               118 non-null    int64
dtypes: datetime64[ns](2), int64(2), object(3)
memory usage: 6.6+ KB

In [9]:
#Filter out discord related issues
df[~df['Text'].str.contains('Discord', case=False, na=False)]

,ID_request,Text,Category,Solution,Date_request_recieved,Date_request_solved,ID_agent
4,4999,Discor needed for instalation.,Discord,Problem solved,2022-10-04,2022-10-04,2
7,4069,Installation needed.,Discord,Software installed,2022-10-10,2022-10-10,1
15,2220,NaN,Discord,Software installed,2022-10-19,2022-10-19,1
16,1308,Asana ist das beste Tool für das Projektmanage...,Asana,Software installed,2022-10-03,2022-10-03,1
17,1089,Bitte installieren Sie Asana erneut auf meinem...,Asana,Asana installed,2022-10-17,2022-10-17,1
...,...,...,...,...,...,...,...
113,2455,Ich möchte eine zusätzliche Tastatur bestellen...,Keyboard,Item sent,2022-10-06,2022-10-06,3
114,3853,Der Tastaturaustausch ist erforderlich. Bitte ...,Keyboard,Item sent,2022-10-17,2022-10-17,3
115,4541,I would like to order the new keyboard for pre...,Keyboard,Item sent,2022-10-19,2022-10-20,2
116,1937,Please send the new keyboard to my home addres...,Keyboard,Item sent,2022-10-04,2022-10-04,3
117,4878,Please send the new keyboard to my home addres...,Keyboard,Item sent,2022-10-17,2022-10-17,1

In [10]:
df['Category'].value_counts()

Category
Outlook             22
Discord             16
CRM                 14
Internet Browser    12
Mail                11
Keyboard            11
Asana               10
Mouse               10
Help Needed          9
Name: count, dtype: int64

In [11]:
df[df['Category'] == 'CRM']

,ID_request,Text,Category,Solution,Date_request_recieved,Date_request_solved,ID_agent
69,4663,Our CRM stopped to work again. I can't start it.,CRM,"Software updated, PC cleaned.",2022-10-03,2022-10-03,2
70,4884,Can't Edit customer field in our CRM. Please f...,CRM,Software reinstalled,2022-10-04,2022-10-04,2
71,2993,Hubspot CRM funktioniert überhaupt nicht. Bitt...,CRM,Software reinstalled,2022-10-24,2022-10-24,3
72,3348,<p>Can't start Salesforce CRM. Please fix this...,CRM,"Software updated, PC cleaned.",2022-10-06,2022-10-06,3
73,2882,CRM funktioniert nach dem letzten Windows-Upda...,CRM,"Software updated, PC cleaned.",2022-10-06,2022-10-06,1
74,2797,Want to add plug-in for Zoom into Hubspot CRM ...,CRM,Premission given,2022-10-03,2022-10-03,3
75,1190,I neeed Salesforce CRM on my new laptop. Pleas...,CRM,Software installed,2022-10-24,2022-10-24,1
76,2686,Ich brauche Salesforce CRM auf meinem neuen La...,CRM,Software installed,2022-10-19,2022-10-19,1
77,2598,"I can't adjust any field in CRM, and I was abl...",CRM,Premission given,2022-10-04,2022-10-06,2
78,1313,"CRM doesn't load customer data, I can't work w...",CRM,Software reinstalled,2022-10-04,2022-10-05,3
79,3620,Installation erforderlich.,CRM,Software installed,2022-10-25,2022-10-25,1
80,4754,I would need Salesforce installed on my PC. I ...,CRM,Software installed,2022-10-17,2022-10-17,2
81,4667,Please fix my CRM. It is not working since yes...,CRM,"Software updated, PC cleaned.",2022-10-03,2022-10-03,3
84,1691,I need to use CRM. Please install it on my pc.,CRM,Software installed,2022-10-11,2022-10-11,1

In [12]:
# Run once if langdetect is not installed
!pip3 install langdetect

Requirement already satisfied: langdetect in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (1.0.9)
Requirement already satisfied: six in /Users/emartinez/Library/Python/3.13/lib/python/site-packages (from langdetect) (1.17.0)

In [13]:
from langdetect import detect, DetectorFactory
DetectorFactory.seed = 0  # For reproducibility

def detect_language(text):
    try:
        if pd.isna(text) or text.strip() == "":
            return "unknown"
        return detect(text)
    except Exception as e:
        return "error unknown"

In [14]:
df['language'] = df['Text'].apply(detect_language)
df['language'].value_counts()

language
en         73
de         35
hr          3
es          2
unknown     1
it          1
sv          1
no          1
da          1
Name: count, dtype: int64

In [ ]:
df3 = df[df['language'] == 'en']

In [18]:
df3.head()

,ID_request,Text,Category,Solution,Date_request_recieved,Date_request_solved,ID_agent,language
1,2691,I need to install Discord on my new PC.,Discord,Discord Installed,2022-10-08,2022-10-10,1,en
2,3395,Discord disappeared from laptop after I update...,Discord,Discord Installed,2022-10-17,2022-10-17,3,en
3,2380,Discord is very slow while other applications ...,Discord,"Software updated, PC cleaned.",2022-10-11,2022-10-11,2,en
4,4999,Discor needed for instalation.,Discord,Problem solved,2022-10-04,2022-10-04,2,en
5,1236,"I can't open Discord, it freezes every time I ...",Discord,Discord installed.,2022-10-19,2022-10-19,2,en

In [19]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Index: 73 entries, 1 to 117
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   ID_request             73 non-null     int64
 1   Text                   73 non-null     object
 2   Category               72 non-null     object
 3   Solution               72 non-null     object
 4   Date_request_recieved  73 non-null     datetime64[ns]
 5   Date_request_solved    73 non-null     datetime64[ns]
 6   ID_agent               73 non-null     int64
 7   language               73 non-null     object
dtypes: datetime64[ns](2), int64(2), object(4)
memory usage: 5.1+ KB

In [ ]:
itdf = pd.read_csv('data/ITSM_Data.csv')