1. For this first dataset [https://www.kaggle.com/datasets/utsav15/it-helpdesk/data](https://www.kaggle.com/datasets/utsav15/it-helpdesk/data), we'll keep the title column and then do some nlp on resolution. Here are the initial thoughs on what the classes will be: 

* password
* network
* account assistance/access
* application/software issue
* user error
* hardware issue
* outage
* security
* needs more details

In [281]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('data/it_clean_data.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,Title,Resolution,class
0,0,0,Need Ethernet access,Please connect the LAN cable to the red port on your workstation. Please write back to IT if you are unable to get the IP addresss,41
1,1,1,Create new account and share the username and password,"Go to URL : accountsetup.com, Enter personal details along with user id, enter OTP received, click finish. Check email for details.",35
2,2,2,FW: Myspace Login Issue-- Ania,"Go to URL : password.reset.com, Enter you login id, enter password received, reset the password",36
3,3,3,Login credetials are not working.,"Go to URL : password.reset.com, Enter you login id, enter password received, reset the password",36
4,4,4,New Account is needed for a new joinee.,"Go to URL : accountsetup.com, Enter personal details along with user id, enter OTP received, click finish. Check email for details.",35

In [282]:
# We're going to drop these columns as there was no documentation on what they were and they don't seem to be relevant to our analysis. 
df1 = df.drop(columns=['Unnamed: 0', 'Unnamed: 0.1','class'])

In [283]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       59 non-null     str
 1   Resolution  59 non-null     str
dtypes: str(2)
memory usage: 1.1 KB

In [284]:
df1[['Title','Resolution']].head()

,Title,Resolution
0,Need Ethernet access,Please connect the LAN cable to the red port on your workstation. Please write back to IT if you are unable to get the IP addresss
1,Create new account and share the username and password,"Go to URL : accountsetup.com, Enter personal details along with user id, enter OTP received, click finish. Check email for details."
2,FW: Myspace Login Issue-- Ania,"Go to URL : password.reset.com, Enter you login id, enter password received, reset the password"
3,Login credetials are not working.,"Go to URL : password.reset.com, Enter you login id, enter password received, reset the password"
4,New Account is needed for a new joinee.,"Go to URL : accountsetup.com, Enter personal details along with user id, enter OTP received, click finish. Check email for details."

In [285]:
# getting the title, and checking for the most frequently used words.
# preprocess > remove punctuation, lowercase, remove stop words, lemmatize
# need to get the most commonly used keywords for classification
import re

all_title1 = ' '.join(df['Title'].astype(str))
all_title1 = all_title1.lower()
words = re.sub(r'[^\w\s]', '', all_title1)
print(len(words))
#print(words)

2364

In [286]:
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.probability import FreqDist
import string

#nltk.download('punkt')
#nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
tokens_no_stop = [word for word in word_tokenize(words) if word not in stop_words]
print(len(tokens_no_stop))
print(tokens_no_stop)

fdist = FreqDist(tokens_no_stop)
print(fdist.most_common(20))

233
['need', 'ethernet', 'access', 'create', 'new', 'account', 'share', 'username', 'password', 'fw', 'myspace', 'login', 'issue', 'ania', 'login', 'credetials', 'working', 'new', 'account', 'needed', 'new', 'joinee', 'request', 'configure', 'system', 'share', 'among', 'users', 'needs', 'permission', 'wifi', 'access', 'laptop', 'lan', 'working', 'vm', 'wifi', 'access', 'needed', 'space', 'qa', 'application', 'configure', 'outlook', 'system', 'install', 'postgres', 'database', 'machine', 'system', 'showing', 'blue', 'screen', 'startup', 'desktop', 'working', 'system', 'behaving', 'strangely', 'blue', 'screen', 'appearing', 'middle', 'internet', 'working', 'account', 'got', 'locked', '3', 'wrong', 'attempts', 'os', 'password', 'could', 'please', 'reset', 'password', 'system', 'hangs', 'blue', 'screen', 'startup', 'unable', 'connect', 'internet', 'facing', 'networkinternet', 'issue', 'wifi', 'xwq090', 'replace', 'battery', 'macbook', 'laptop', 'computer', 'getting', 'switched', 'forgot', 'password', 'please', 'reset', 'password', 'myspace', 'password', 'expiry', 'install', 'ms', 'office', 'password', 'expired', 'account', 'locked', 'able', 'login', 'spaces', 'allowed', 'email', 'addresses', 'virus', 'damage', 'computer', 'hardware', 'windows', 'come', 'virus', 'protection', 'program', 'clean', 'keyboard', 'recover', 'file', 'recycle', 'bin', 'update', 'microsoft', 'windows', 'computer', 'delete', 'internet', 'cookies', 'determine', 'computers', 'name', 'fix', 'paper', 'jam', 'get', 'safe', 'mode', 'map', 'network', 'drive', 'unable', 'send', 'receive', 'email', 'cant', 'connect', 'network', 'drive', 'anymore', 'cant', 'delete', 'file', 'used', 'windows', 'cant', 'receive', 'email', 'attachments', 'get', 'signal', 'input', 'message', 'lost', 'printer', 'installation', 'disk', 'install', 'printer', 'format', 'erase', 'hard', 'drive', 'remove', 'virus', 'safe', 'turn', 'windows', 'computer', 'without', 'shut', 'computer', 'doesnt', 'power', 'computer', 'freezes', 'behaving', 'strangely', 'computer', 'turn', 'printer', 'printing', 'smudgeddistorted', 'pages', 'nothing', 'appears', 'monitor', 'wheel', 'mouse', 'isnt', 'working', 'properly', 'black', 'borders', 'screen', 'display', 'monitor', 'hard', 'disk', 'fails', 'work', 'image', 'screen', 'distorted', 'skewed', 'computer', 'crashes', 'computer', 'virus', 'mouse', 'acting', 'erratically']
[('computer', 9), ('password', 7), ('working', 5), ('system', 5), ('screen', 5), ('account', 4), ('virus', 4), ('windows', 4), ('access', 3), ('new', 3), ('login', 3), ('wifi', 3), ('install', 3), ('blue', 3), ('internet', 3), ('email', 3), ('drive', 3), ('cant', 3), ('printer', 3), ('share', 2)]

In [287]:
#!pip install openpyxl

In [288]:
it2 = pd.read_excel('data/SampleInput.xlsx')
it2.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,TicketNumber,Client,Staff,Source,Title,Resolution,HelpTopic,DataOn,DueDate,ClosedDate,ModifiedDate,KYC
1,T955496,User,ITSupport,Email,Need Ethernet access,Please connect the LAN cable to the red port on your workstation. Please write back to IT if you are unable to get the IP addresss,Network & Wireless,12/17/15 12:00 PM,NaN,12/17/15 01:02 PM,12/17/15 12:59 PM,YY
2,IT413956,User,ITSupport,Email,Need a LAN Cable,Please come to IT desk and collect.,Accessories,14-12-2017 12:06,NaN,15-12-2017 13:13,14-12-2017 12:42,N
3,IT413444,User,ITSupport,Email,Need a laptop Conector.,Please come to IT desk and collect.,Accessories,14-12-2017 12:06,NaN,15-12-2017 13:13,14-12-2017 13:44,N
4,IT413923,User,ITSupport,Email,Need a mouse,hello Raj Ganpur<br /><br />please come to It desk and collect the mouse.,Accessories,14-12-2017 12:06,NaN,15-12-2017 13:13,15-12-2017 12:15,N

In [289]:
it2.info()

<class 'pandas.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   399 non-null    str
 1   Unnamed: 1   399 non-null    str
 2   Unnamed: 2   399 non-null    str
 3   Unnamed: 3   399 non-null    str
 4   Unnamed: 4   274 non-null    str
 5   Unnamed: 5   399 non-null    str
 6   Unnamed: 6   399 non-null    str
 7   Unnamed: 7   399 non-null    object
 8   Unnamed: 8   1 non-null      str
 9   Unnamed: 9   399 non-null    object
 10  Unnamed: 10  399 non-null    object
 11  Unnamed: 11  395 non-null    str
dtypes: object(3), str(9)
memory usage: 37.5+ KB

In [ ]:
# Lets subset this data to just the columns we need. 
it3  = it2[['Unnamed: 4','Unnamed: 5','Unnamed: 6']]
it3.head()

,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,Title,Resolution,HelpTopic
1,Need Ethernet access,Please connect the LAN cable to the red port on your workstation. Please write back to IT if you are unable to get the IP addresss,Network & Wireless
2,Need a LAN Cable,Please come to IT desk and collect.,Accessories
3,Need a laptop Conector.,Please come to IT desk and collect.,Accessories
4,Need a mouse,hello Raj Ganpur<br /><br />please come to It desk and collect the mouse.,Accessories

In [291]:
# Let's rename the columns and reset the index. Then drop the first 2 columns.
it3.columns = it3.iloc[0]
it3 = it3.iloc[1:].reset_index(drop=True)
it3.info()
#it3 = it3.drop(columns=['Unnamed: 0.1','Unnamed: 0^','class'])

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       273 non-null    str
 1   Resolution  398 non-null    str
 2   HelpTopic   398 non-null    str
dtypes: str(3)
memory usage: 9.5 KB

In [292]:
it2['Unnamed: 6'].value_counts()

Unnamed: 6
Access Requests                          243
Accessories                              128
Network & Wireless                         7
Hardware Issue                             3
Data Center Services /Report VM issue      2
Software Request                           2
Email Services                             2
Hardware                                   2
Network                                    2
HelpTopic                                  1
VPN access                                 1
Jira Requests                              1
Data Center Services                       1
Data Center Services /VM Request           1
Newhire Accounts                           1
Password Reset                             1
Software Installation & Configuration      1
Name: count, dtype: int64

In [293]:
# Let's merge our two datasets together and see if we can find any insights.
it_clean = pd.merge(df1, it3, on=['Title','Resolution'], how='outer')
it_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 430 entries, 0 to 429
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       305 non-null    str
 1   Resolution  430 non-null    str
 2   HelpTopic   398 non-null    str
dtypes: str(3)
memory usage: 10.2 KB

In [294]:
# Check for certain text in the title and check for phrases
it_clean[it_clean['Title'].str.contains('login', case=False, na=False)].value_counts()

Title                                                               Resolution                                                                                       HelpTopic
Account locked. Not able to login                                   Unlocked the account and new password is sent to your email id.                                  Access Requests    1
FW: Myspace Login Issue-- Ania                                      Go to URL : password.reset.com, Enter you login id, enter password received, reset the password  Access Requests    1
Login Page Down                                                     Login server was down. It is up now. Please check.                                               Access Requests    1
Login Page is not getting displayed                                 Login server was down. It is up now. Please check.                                               Access Requests    1
Login Page not opening                                              Login server was down. It is up now. Please check.                                               Access Requests    1
Login credetials are not working, says username or password wrong.  Password got expired. New password is sent to your email id                                      Access Requests    1
Login credetials are not working.                                   Go to URL : password.reset.com, Enter you login id, enter password received, reset the password  Access Requests    1
Request to create login credentials for Dr. Hasan                   Account created and details sent to user's personal email ID                                     Access Requests    1
Request to create login credentials for Mr. Koti                    We have already created account and details have been sent to his personal Email ID              Access Requests    1
Name: count, dtype: int64

In [295]:
# Some ticket titles were more of ticket status updates, so we will remove those.
invalid_titles = ['Status Changed','Collaborators added by end user','Ticket Marked Overdue','Ticket Updated','Ticket Assigned to Sandeep Reddy Jakkidi','Ticket Assigned to Shijil Kumar Aynoli','Ticket Assigned to Pavan Kumar Thukuntla','Ticket Assigned to Shashi Kumar Raju Hasthi', 'Ticket Assigned to Kishore Babu Ganesana', 'Ticket Assigned to N V R S Surya Narayana Garlapati','New Collaborator Added', 'Ticket Assigned to Janardhana Rao Vemulapalli','Ticket Assigned to Nagaraju Mochi', 'Ticket Assigned to Vinod Kumar Reddy Dendi', 'New Ticket by Agent','Ticket Assigned to Anil Kumar Thanjavuru']
it_all_titles = it_clean[~it_clean['Title'].isin(invalid_titles)]
it_all_titles = ' '.join(it_all_titles['Title'].dropna().astype(str))
it_all_titles = it_all_titles.lower()
it_all_titles_clean = re.sub(r'[^\w\s]', '', it_all_titles)
print(len(it_all_titles_clean))

# Tokenize the titles and remove stop words.
tokens_no_stop2 = [word for word in word_tokenize(it_all_titles_clean) if word not in stop_words]
print(len(tokens_no_stop2))
print(tokens_no_stop2)

# Let's get frequency counts
fdist2 = FreqDist(tokens_no_stop2)
print(fdist2.most_common(20))

3728
403
['account', 'got', 'locked', '3', 'wrong', 'attempts', 'os', 'password', 'could', 'please', 'reset', 'password', 'account', 'locked', 'able', 'login', 'spaces', 'allowed', 'email', 'addresses', 'virus', 'damage', 'computer', 'hardware', 'computer', 'getting', 'switched', 'configure', 'outlook', 'system', 'create', 'new', 'account', 'share', 'username', 'password', 'creation', 'mail', 'id', 'new', 'joinee', 'desktop', 'working', 'windows', 'come', 'virus', 'protection', 'program', 'fw', 'myspace', 'login', 'issue', 'ania', 'facing', 'networkinternet', 'issue', 'wifi', 'xwq090', 'file', 'import', 'error', 'file', 'import', 'error', 'file', 'import', 'error', 'file', 'import', 'error', 'forgot', 'password', 'please', 'reset', 'password', 'clean', 'keyboard', 'recover', 'file', 'recycle', 'bin', 'update', 'microsoft', 'windows', 'computer', 'delete', 'internet', 'cookies', 'determine', 'computers', 'name', 'fix', 'paper', 'jam', 'get', 'safe', 'mode', 'map', 'network', 'drive', 'unable', 'send', 'receive', 'email', 'cant', 'connect', 'network', 'drive', 'anymore', 'cant', 'delete', 'file', 'used', 'windows', 'cant', 'receive', 'email', 'attachments', 'get', 'signal', 'input', 'message', 'lost', 'printer', 'installation', 'disk', 'install', 'printer', 'format', 'erase', 'hard', 'drive', 'remove', 'virus', 'install', 'microsoft', 'outlook', 'install', 'postgres', 'database', 'machine', 'safe', 'turn', 'windows', 'computer', 'without', 'shut', 'jira', 'project', 'creation', 'user', 'permission', 'lan', 'working', 'vm', 'linux', 'vm', 'azuba', 'project', 'login', 'page', 'login', 'page', 'getting', 'displayed', 'login', 'page', 'opening', 'login', 'credetials', 'working', 'says', 'username', 'password', 'wrong', 'login', 'credetials', 'working', 'mailbox', 'full', 'mouse', 'replacement', 'needed', 'computer', 'doesnt', 'power', 'computer', 'freezes', 'behaving', 'strangely', 'internet', 'working', 'space', 'qa', 'application', 'computer', 'turn', 'printer', 'printing', 'smudgeddistorted', 'pages', 'myspace', 'password', 'expiry', 'name', 'correction', 'mail', 'id', 'need', 'ethernet', 'access', 'need', 'wave', 'rock', 'vpn', 'need', 'wifi', 'access', 'approval', 'need', 'lan', 'cable', 'need', 'laptop', 'conector', 'need', 'mouse', 'need', 'abc', 'ftp', 'server', 'details', 'need', 'administration', 'acess', 'installing', 'softwares', 'system', 'needs', 'permission', 'wifi', 'access', 'laptop', 'new', 'account', 'needed', 'new', 'joinee', 'able', 'proceed', 'ticketabccom', 'logging', 'nothing', 'appears', 'monitor', 'password', 'expired', 'prvide', 'admini', 'privileges', 'install', 'mysql', 'database', 'prvide', 'admini', 'privileges', 'install', 'mysql', 'database', 'public', 'ip', 'address', 'coffee', 'house', 'project', 'unable', 'access', 'outlook', 'myspace', 'user', 'id', 'sdash', 'removing', 'person', 'adding', 'person', 'b', 'abc', 'project', 'replace', 'battery', 'macbook', 'laptop', 'request', 'configure', 'system', 'share', 'among', 'users', 'request', 'create', 'login', 'credentials', 'dr', 'hasan', 'request', 'create', 'login', 'credentials', 'mr', 'koti', 'system', 'behaving', 'strangely', 'blue', 'screen', 'appearing', 'middle', 'system', 'hangs', 'blue', 'screen', 'startup', 'system', 'showing', 'blue', 'screen', 'startup', 'wheel', 'mouse', 'isnt', 'working', 'properly', 'black', 'borders', 'screen', 'display', 'monitor', 'ticket', 'assigned', 'hari', 'neelam', 'ticket', 'assigned', 'jagan', 'muddupati', 'ticket', 'assigned', 'kumara', 'swamy', 'annepu', 'usb', 'enabling', 'unable', 'connect', 'internet', 'unable', 'connect', 'internet', 'using', 'wifi', 'network', 'inn009', 'unable', 'connect', 'internet', 'using', 'wifi', 'network', 'inn009', 'unable', 'install', 'outlook', 'asking', 'admin', 'access', 'needed', 'hard', 'disk', 'fails', 'work', 'image', 'screen', 'distorted', 'skewed', 'computer', 'crashes', 'computer', 'virus', 'mouse', 'acting', 'erratically', 'wifi', 'access', 'needed', 'install', 'ms', 'office', 'server11', 'got', 'hanged', 'needed', 'restart']
[('login', 9), ('computer', 9), ('password', 8), ('need', 8), ('install', 7), ('system', 6), ('working', 6), ('wifi', 6), ('file', 6), ('unable', 6), ('access', 6), ('internet', 5), ('needed', 5), ('screen', 5), ('account', 4), ('virus', 4), ('outlook', 4), ('new', 4), ('windows', 4), ('import', 4)]

These values are simliar to the ones I have thought about.  I will align the final dataset to include the following issue types:
* Access Requests (include new hire and termination requests)
* Password Resets
* Accessories
* Hardware issue
* Software issue
* Security (malware detection, unauthorized access)
* Network
* Needs more information
* Service outage
* Misc (other) issues

In [296]:
# The following dataset is also from Kaggle:
# https://www.kaggle.com/datasets/tobiasbueck/multilingual-customer-support-tickets
# We will subset this dataset to include Engligh and 'IT Support' tickets 
csit = pd.read_csv('data/cs-it/aa_dataset-tickets-multi-lang-5-2-50-version.csv')

In [297]:
csit.info()

<class 'pandas.DataFrame'>
RangeIndex: 28587 entries, 0 to 28586
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   subject   24749 non-null  str
 1   body      28587 non-null  str
 2   answer    28580 non-null  str
 3   type      28587 non-null  str
 4   queue     28587 non-null  str
 5   priority  28587 non-null  str
 6   language  28587 non-null  str
 7   version   28587 non-null  int64
 8   tag_1     28587 non-null  str
 9   tag_2     28574 non-null  str
 10  tag_3     28451 non-null  str
 11  tag_4     25529 non-null  str
 12  tag_5     14545 non-null  str
 13  tag_6     5874 non-null   str
 14  tag_7     2040 non-null   str
 15  tag_8     565 non-null    str
dtypes: int64(1), str(15)
memory usage: 3.5 MB

In [298]:
csit = csit[(csit['language'] == "en") & (csit['queue'] == "IT Support")]
#csit.head()
csit.info()

<class 'pandas.DataFrame'>
Index: 1942 entries, 12 to 28585
Data columns (total 16 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   subject   1609 non-null   str
 1   body      1942 non-null   str
 2   answer    1942 non-null   str
 3   type      1942 non-null   str
 4   queue     1942 non-null   str
 5   priority  1942 non-null   str
 6   language  1942 non-null   str
 7   version   1942 non-null   int64
 8   tag_1     1942 non-null   str
 9   tag_2     1941 non-null   str
 10  tag_3     1938 non-null   str
 11  tag_4     1768 non-null   str
 12  tag_5     1001 non-null   str
 13  tag_6     363 non-null    str
 14  tag_7     111 non-null    str
 15  tag_8     37 non-null     str
dtypes: int64(1), str(15)
memory usage: 257.9 KB

In [299]:
# let's remove the tags that were used for auto tagging in the original dataset as they aren't relevant to our analysis.
# we'll also remove the other irrelevant fields and we already filtered out for english language and IT support queue.
csit_clean = csit.drop(columns=['tag_1','tag_2','tag_3','tag_4','tag_5','tag_6','tag_7','tag_8','queue','priority','language','type','version'])
csit_clean.dropna(inplace=True)
csit_clean.info()

<class 'pandas.DataFrame'>
Index: 1609 entries, 12 to 28585
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   subject  1609 non-null   str
 1   body     1609 non-null   str
 2   answer   1609 non-null   str
dtypes: str(3)
memory usage: 50.3 KB

In [300]:
csit_clean.head()

,subject,body,answer
12,Immediate Help Needed: Technical Problem with Cloud SaaS Service,"Dear Customer Support Team,\n\nI am submitting a report regarding a technical problem encountered with the Cloud SaaS platform, which is currently disrupting our business activities. I have observed that certain features are not functioning as expected, causing interruptions that hinder workflow efficiency.\n\nIn particular, I am facing sporadic connectivity issues when trying to access the platform. Sometimes, the system fails to load the dashboard, and the data displayed appears outdated or incomplete. Furthermore, the response times for executing commands have significantly increased, resulting in delays.","Thanks for providing detailed information about the issue with the Cloud SaaS platform. We apologize for the inconvenience and understand the impact on your business. To assist us further, could you please confirm if the problem is affecting specific user accounts, and share any relevant error messages or screenshots? Also, let us know your current browser and operating system versions. Our technical team is ready to escalate this matter and work towards a swift resolution. Feel free to contact us by phone if needed."
23,Multiple Device Connection Problems,"Dear Customer Support,\n\nWe are experiencing extensive connectivity problems impacting numerous devices throughout the office. The issues have been observed with headsets, printers, and workstations all at once, significantly disrupting daily activities. Our initial investigation indicates that the cause may be a network outage or a misconfiguration within the system infrastructure.\n\nOur team has already tried several troubleshooting methods, including rebooting affected devices and swapping hardware components, but unfortunately, these efforts did not resolve the disruptions.","Thank you for providing details about the connectivity problems affecting various devices. To assist you further, could you please specify whether the network outage affects both wired and wireless connections, and if any error messages are displayed on the devices? Also, kindly inform us of any recent modifications to your network configuration or infrastructure. If possible, please share relevant network logs or screenshots. We will prioritize your case and, if necessary, arrange a call at your convenience to accelerate the troubleshooting process."
50,Overheating Concern,"Dear Customer Support Team,\n\nI am submitting a report about a critical issue in the server room that demands immediate action. There are severe overheating problems, seemingly caused by a malfunctioning PC fan (PC-Lüfter). Despite attempts to control the situation, the issue persists, leading to increased temperatures that could potentially harm the hardware.\n\nTo resolve this, I have already tried several restart cycles and performed basic cleaning to remove dust accumulation. However, the problem remains unresolved.","We appreciate your detailed report regarding the overheating problem in the server room and the non-operational PC fan. Based on your description and the troubleshooting steps already taken, it seems the fan may need professional inspection and possibly replacement. Please confirm the make and model of the affected system, and let us know your preferred time for a technician to visit. In the meantime, ensure the server room is properly ventilated and, if possible, reduce the server workload to lower heat generation. Disconnect any non-essential equipment as well."
65,Network Connectivity Problems Impacting Medical Equipment,"Dear Support Team,\n\nI am writing to report a critical problem affecting several linked healthcare devices on our network. These devices are currently facing severe connectivity and performance issues, which are disrupting our daily activities. I suspect that recent updates to security policies or modifications to network configurations may be the cause.\n\nIn an effort to resolve the issue, I have already restarted the affected equipment and thoroughly reviewed the network settings; however, the problem continues without any improvement.","Thank you for reaching out regarding the connectivity problems with your healthcare equipment. To assist you more effectively, could you please provide details such as the specific device models affected, any error messages encountered, and when the issue initially started? Also, inform us of any recent changes made to network security policies. If an urgent response by phone is preferred, kindly share a suitable time and contact number so we can call you. We will prioritize your request for assistance."
74,Product Assistance Request,"Dear Customer Service Team,\n\nI hope this message reaches you in good health. I am reaching out to inquire about the support procedures for a recent purchase from your company. As a valued client, I want to ensure I understand the correct steps to follow if I encounter any problems or need help with the product.\n\nCould you please provide comprehensive details about the support process? Specifically, I would appreciate instructions on how to start a support request, expected response times, and any necessary documentation or proof required.",Kindly specify the model of the product.

In [301]:
pd.set_option('display.max_colwidth', None)
csit_clean['subject']

12                     Immediate Help Needed: Technical Problem with Cloud SaaS Service
23                                                  Multiple Device Connection Problems
50                                                                  Overheating Concern
65                            Network Connectivity Problems Impacting Medical Equipment
74                                                           Product Assistance Request
                                              ...
28437                                                       Team Collaboration Software
28471    Improve Digital Marketing Tactics for Enhanced Brand Expansion and Interaction
28473                          Alert on Unauthorized Access Attempt in Hospital Systems
28575                                            Critical Error in Data Syncing Process
28585                             Update Request for SaaS Platform Integration Features
Name: subject, Length: 1609, dtype: str

In [302]:
csit_all_titles = ' '.join(csit_clean['subject'].dropna().astype(str))
# remove punctuation
csit_all_titles_clean = re.sub(r'[^\w\s]', '', csit_all_titles)

# Tokenize the titles and remove stop words.
csit_tokens_no_stop = [word for word in word_tokenize(csit_all_titles_clean) if word not in stop_words]
print(len(csit_tokens_no_stop))
print(csit_tokens_no_stop)

# Let's get frequency counts
csit_fdist = FreqDist(csit_tokens_no_stop)
print(csit_fdist.most_common(20))

7708

In [303]:
# Check for certain text in the title and check for phrases
csit_clean[csit_clean['subject'].str.contains('windows', case=False, na=False)].value_counts()

subject                                  body                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          answer
Login Problem on Windows 10              Dear Customer Support,\n\nI'm facing difficulties when trying to access my Windows 10 Pro device. Each login attempt results in the system either hanging or displaying an error message that blocks access. I've rebooted several times and checked that my keyboard functions correctly, but the issue continues. This problem is significantly affecting my work since I can't open files or use applications. Could you please help me resolve this login issue as soon as possible? Here are some troubleshooting steps I've taken.                      Thank you for reaching out regarding your login trouble with your Windows 10 Pro device. To assist you better, could you specify the exact error message you see during login? Additionally, do you log in using a local account or a Microsoft account? If possible, try booting your computer in Safe Mode by repeatedly pressing F8 during startup. Please let us know if this allows you to log in. If not, kindly provide us with recent error details or screenshots to further diagnose the issue.                                                                                                             1
Login Problems with Windows 10           Dear Customer Support,\n\nI am facing difficulties when trying to access my Windows 10 Pro device. Each login attempt results in the system either becoming unresponsive or showing an error message that blocks access. I have rebooted several times and verified that my keyboard functions correctly, but the issue remains. This problem is significantly affecting my productivity as I cannot reach my files or applications. Could you please help me resolve this login issue as soon as possible? Here are the troubleshooting steps I have tried.  Thank you for reaching out regarding your login difficulties with your Windows 10 Pro device. To assist you better, could you specify the exact error message you encounter during login? Additionally, are you attempting to log in with a local account or a Microsoft account? If possible, try booting your computer into Safe Mode by repeatedly pressing F8 during startup. Please let us know if this resolves the issue. If not, kindly provide recent details or error messages to help us diagnose further.                                                                                                 1
Issues with Digital Tools on Windows 10  The digital tools used by the marketing agency are not functioning properly, leading to delays in campaigns. There may be software conflicts on Windows 10 Pro. Attempts to troubleshoot through updates have not resolved the problem. Assistance is needed to resolve this issue.                                                                                                                                                                                                                                                                           <name>, I am writing to acknowledge the report regarding the malfunctioning of digital tools on Windows 10 Pro at your marketing agency. I understand the urgency of resolving this matter to prevent further campaign delays. To better assist you, could you please share the troubleshooting steps you have already performed and any specific error messages you have encountered? Additionally, I would like to arrange a call at your convenience to discuss this further. Please let me know a suitable time to contact you at <tel_num>. We are committed to identifying and resolving the issue promptly.    1
Name: count, dtype: int64

I'm leaning more torwards taking a subset of the data that we can use.  The frequency counts don't appear to be simliar in this dataset. For now, we'l use the it_clean dataset and then add to it later.

In [304]:
it_clean = it_clean.rename(columns={'HelpTopic': 'Type'})
it_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 430 entries, 0 to 429
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Title       305 non-null    str
 1   Resolution  430 non-null    str
 2   Type        398 non-null    str
dtypes: str(3)
memory usage: 10.2 KB

In [305]:
# fill in missing values with 'Unknown'
it_clean['Title'] = it_clean['Title'].fillna('Unknown')
it_clean['Type'] = it_clean['Type'].fillna('Unknown')

# let's check the 'Type' values and recategorize them
it_clean['Type'].value_counts()
it_clean['Type'] = it_clean['Type'].replace({
    'Software Installation & Configuration': 'software',
    'Software Request': 'software',
    'Hardware Issue': 'hardware',
    'Network Issue': 'network',
    'Network & Wireless': 'network',
    'Access Issue': 'access request',
    'Access Request': 'access request',
    'VPN access': 'access request',
    'Newhire Accounts': 'access request',
    'Access Requests': 'access request',
    'Jira Requests': 'other',
    'Email Services': 'other',
    'Data Center Services /Report VM issue':'platform',
    'Data Center Services /VM Request':'platform',
    'Data Center Services':'platform',
})
it_clean.loc[it_clean['Title'].str.contains('password', case=False, na=False), 'Type'] = 'Password Reset'
it_clean['Type'].value_counts()

Type
access request    240
Accessories       128
Unknown            32
network             7
Password Reset      6
platform            4
hardware            3
other               3
software            3
Network             2
Hardware            2
Name: count, dtype: int64

In [ ]:
# Let's manually inspect the unknown types and manualy reclassify them if possible.
it_clean[it_clean['Type'] == 'Unknown'][['Title','Type']]
#it_clean.loc[it_clean['Title'].str.contains('virus', case=False, na=False), 'Type'] = 'security'
#it_clean.loc[2, 'Type'] = 'Access'
it_clean.loc[56, 'Type'] = 'hardware'
it_clean.loc[59, 'Type'] = 'system'
it_clean.loc[61, 'Type'] = 'printer'
it_clean.loc[62, 'Type'] = 'system'
it_clean.loc[63, 'Type'] = 'system'
it_clean.loc[65, 'Type'] = 'system'
it_clean.loc[66, 'Type'] = 'system'
it_clean.loc[68, 'Type'] = 'system'
it_clean.loc[84, 'Type'] = 'system'
it_clean.loc[85, 'Type'] = 'system'
it_clean.loc[88, 'Type'] = 'system'
it_clean.loc[169, 'Type'] = 'hardware'
it_clean.loc[170, 'Type'] = 'system'
it_clean.loc[171, 'Type'] = 'system'
it_clean.loc[297, 'Type'] = 'system'
it_clean.loc[298, 'Type'] = 'system'
it_clean.loc[111, 'Type'] = 'system'
it_clean.loc[299, 'Type'] = 'system'
it_clean.loc[301, 'Type'] = 'system'
it_clean[it_clean['Type'] == 'Unknown'][['Title','Type']]

In [306]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix 

X = it_clean['Title']
y = it_clean['Type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [307]:
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(
        stop_words="english",
        ngram_range=(1,2),
    )),
    ('clf', LogisticRegression(max_iter=100, random_state=42))
])
pipeline.fit(X_train,y_train)

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(ngram_range=(1, 2), stop_words='english')),
                ('clf', LogisticRegression(random_state=42))])

In [308]:
y_pred = pipeline.predict(X_test)
print(classification_report(y_test, y_pred))

                precision    recall  f1-score   support

   Accessories       0.40      0.08      0.13        26
Password Reset       0.00      0.00      0.00         1
       Unknown       1.00      0.17      0.29         6
access request       0.56      0.94      0.70        48
      hardware       0.00      0.00      0.00         1
       network       0.00      0.00      0.00         1
         other       0.00      0.00      0.00         1
      platform       0.00      0.00      0.00         1
      software       0.00      0.00      0.00         1

      accuracy                           0.56        86
     macro avg       0.22      0.13      0.12        86
  weighted avg       0.50      0.56      0.45        86

/opt/miniconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/opt/miniconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

,Title,Type
2,Are spaces allowed in email addresses?,Unknown
57,How can I recover a file from the recycle bin?,Unknown
58,How can I update my Microsoft Windows computer?,Unknown
60,How do I determine my computer's name?,Unknown
64,I am unable to send or receive email?,Unknown
67,I can't receive any email attachments?,Unknown
73,Is it safe to turn off a Windows computer without doing a shut down?,Unknown